{"ast":null,"code":"import _classCallCheck from \"C:\\\\Users\\\\Digivox\\\\dev\\\\Digivox\\\\Refatoracao\\\\squad\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/classCallCheck\";\nimport _assertThisInitialized from \"C:\\\\Users\\\\Digivox\\\\dev\\\\Digivox\\\\Refatoracao\\\\squad\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/assertThisInitialized\";\nimport _inherits from \"C:\\\\Users\\\\Digivox\\\\dev\\\\Digivox\\\\Refatoracao\\\\squad\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/inherits\";\nimport _createSuper from \"C:\\\\Users\\\\Digivox\\\\dev\\\\Digivox\\\\Refatoracao\\\\squad\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/createSuper\";\nimport _wrapNativeSuper from \"C:\\\\Users\\\\Digivox\\\\dev\\\\Digivox\\\\Refatoracao\\\\squad\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/wrapNativeSuper\";\n\n/**\n * An Exception is considered a condition that a reasonable application may wish to catch.\n * An Error indicates serious problems that a reasonable application should not try to catch.\n * @public\n */\nexport var Exception = /*#__PURE__*/function (_Error) {\n  _inherits(Exception, _Error);\n\n  var _super = _createSuper(Exception);\n\n  function Exception(message) {\n    var _this;\n\n    _classCallCheck(this, Exception);\n\n    _this = _super.call(this, message); // 'Error' breaks prototype chain here\n\n    Object.setPrototypeOf(_assertThisInitialized(_this), (this instanceof Exception ? this.constructor : void 0).prototype); // restore prototype chain\n\n    return _this;\n  }\n\n  return Exception;\n}( /*#__PURE__*/_wrapNativeSuper(Error));","map":{"version":3,"sources":["C:/Users/Digivox/dev/Digivox/Refatoracao/squad/node_modules/sip.js/lib/core/exceptions/exception.js"],"names":["Exception","message","Object","setPrototypeOf","prototype","Error"],"mappings":";;;;;;AAAA;AACA;AACA;AACA;AACA;AACA,WAAaA,SAAb;AAAA;;AAAA;;AACI,qBAAYC,OAAZ,EAAqB;AAAA;;AAAA;;AACjB,8BAAMA,OAAN,EADiB,CACD;;AAChBC,IAAAA,MAAM,CAACC,cAAP,gCAA4B,wDAAWC,SAAvC,EAFiB,CAEkC;;AAFlC;AAGpB;;AAJL;AAAA,iCAA+BC,KAA/B","sourcesContent":["/**\n * An Exception is considered a condition that a reasonable application may wish to catch.\n * An Error indicates serious problems that a reasonable application should not try to catch.\n * @public\n */\nexport class Exception extends Error {\n    constructor(message) {\n        super(message); // 'Error' breaks prototype chain here\n        Object.setPrototypeOf(this, new.target.prototype); // restore prototype chain\n    }\n}\n"]},"metadata":{},"sourceType":"module"}